---
title: "__Bayesian_nonparamterics"
output: html_document
date: "2023-08-17"
---


# Note: Run this code after running "___new_clustering.rmd"!


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)


library(maotai) # DP-means algorithm
```




```{r run dp-means}

library(maotai)
# dpmeans(data = data_clustering_num, 
#                 lambda = ,
#                 maxiter = 1000,
#                 permute.order = TRUE)



lab = c(rep(1,50),rep(2,50))


delta <- data_clustering_num$delta
beta <- data_clustering_num$beta
dictator <- data_clustering_num$dictator
dictator_schoolmate <- data_clustering_num$dictator_schoolmate
risk <- data_clustering_num$risk
publicgood <- data_clustering_num$publicgood
trust <- data_clustering_num$trust
trust_return <- data_clustering_num$trust_return

X_dataclustering<- rbind(delta,beta,dictator,dictator_schoolmate,risk,publicgood,trust,trust_return)


## run dpmeans with several lambda values
solA <- dpmeans(X_dataclustering, lambda= 30)$cluster
solB <- dpmeans(X_dataclustering, lambda=500)$cluster
solC <- dpmeans(X_dataclustering, lambda=1000)$cluster

## visualize the results

# to visualize, we use UMAP

X <- data.frame(UMAP1= umap_dimensions$UMAP1,
                   UMAP2 = umap_dimensions$UMAP2)

opar <- par(no.readonly=TRUE)
par(mfrow=c(1,4), pty="s")
plot(X,col=lab,  pch=19, cex=.8, main="True", xlab="x", ylab="y")
plot(X,col=solA, pch=19, cex=.8, main="dpmeans lbd=5", xlab="x", ylab="y")
plot(X,col=solB, pch=19, cex=.8, main="dpmeans lbd=10", xlab="x", ylab="y")
plot(X,col=solC, pch=19, cex=.8, main="dpmeans lbd=20", xlab="x", ylab="y")
par(opar)
```


```{r}



sol8 <- list()
for (i in lambda_param){
  sol8[[i]] = dpmeans(X_dataclustering, lambda=, permute.order=TRUE)$cluster
}

## let's visualize
vpar <- par(no.readonly=TRUE)
par(mfrow=c(2,4), pty="s")
for (i in 1:8){
  pm = paste("permute no.",i,sep="")
  plot(X,col=sol8[[i]], pch=19, cex=.8, main=pm, xlab="x", ylab="y")
}
par(vpar)
```







